use crate::domain::Component;

const SCRIPT_HEADER: &str = r#"#!/usr/bin/env bash
set -euo pipefail

# Generated by jlo setup
# Do not edit manually - regenerate with 'jlo setup gen'

"#;

/// Generate install.sh content from resolved components.
pub fn generate(components: &[Component]) -> String {
    let mut parts = vec![SCRIPT_HEADER.to_string()];

    for component in components {
        parts.push(
            "# =============================================================================="
                .to_string(),
        );
        parts.push(format!("# {}: {}", component.name, component.summary));
        parts.push(
            "# =============================================================================="
                .to_string(),
        );
        parts.push(String::new());

        let content = component.script_content.trim();
        let cleaned_content = content
            .lines()
            .filter(|line| !line.starts_with("#!/") && !line.starts_with("set -"))
            .collect::<Vec<_>>()
            .join("\n");

        parts.push(cleaned_content.trim().to_string());
        parts.push(String::new());
        parts.push(String::new());
    }

    parts.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::ComponentId;

    fn make_component(name: &str) -> Component {
        Component {
            name: ComponentId::new(name).unwrap(),
            summary: format!("{} component", name),
            dependencies: vec![],
            env: vec![],
            script_content: format!("echo {}", name),
        }
    }

    #[test]
    fn generate_script_with_header() {
        let components = vec![make_component("test")];

        let script = generate(&components);

        assert!(script.starts_with("#!/usr/bin/env bash"));
        assert!(script.contains("set -euo pipefail"));
        assert!(script.contains("Generated by jlo setup"));
    }

    #[test]
    fn generate_script_with_sections() {
        let components = vec![make_component("alpha"), make_component("beta")];

        let script = generate(&components);

        assert!(script.contains("# alpha: alpha component"));
        assert!(script.contains("# beta: beta component"));
        assert!(script.contains("echo alpha"));
        assert!(script.contains("echo beta"));
    }
}
