name: 'Setup Rust Environment'
description: 'Checks out code, installs Rust, and caches Cargo dependencies'
inputs:
  rust-version:
    description: 'Rust toolchain version'
    required: false
    default: ''
  components:
    description: 'Rust toolchain components to install (comma-separated, e.g., rustfmt,clippy)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Determine Rust Version
      id: version
      shell: bash
      run: |
        if [ -n "${{ inputs.rust-version }}" ]; then
          echo "toolchain=${{ inputs.rust-version }}" >> $GITHUB_OUTPUT
        elif [ -f "rust-toolchain.toml" ]; then
          # Simple extraction of channel from TOML
          channel=$(grep -E '^channel\s*=' rust-toolchain.toml | sed -E 's/channel\s*=\s*"([^"]+)"/\1/')
          if [ -n "$channel" ]; then
            echo "toolchain=$channel" >> $GITHUB_OUTPUT
          else
            echo "::error::Could not parse channel from rust-toolchain.toml"
            exit 1
          fi
        elif [ -f "rust-toolchain" ]; then
          channel=$(cat rust-toolchain | tr -d '[:space:]')
          echo "toolchain=$channel" >> $GITHUB_OUTPUT
        else
          echo "::error::No rust-version input and no toolchain file found"
          exit 1
        fi

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
      with:
        toolchain: ${{ steps.version.outputs.toolchain }}
        components: ${{ inputs.components }}

    - name: Cache Cargo dependencies
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
