name: 'Setup Rust Environment'
description: 'Checks out code, installs Rust, and caches Cargo dependencies'
inputs:
  rust-version:
    description: 'Rust toolchain version'
    required: false
  components:
    description: 'Rust toolchain components to install (comma-separated, e.g., rustfmt,clippy)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Resolve Rust Version
      id: version
      shell: bash
      env:
        INPUT_RUST_VERSION: ${{ inputs.rust-version }}
      run: |
        if [ -n "$INPUT_RUST_VERSION" ]; then
          echo "toolchain=$INPUT_RUST_VERSION" >> $GITHUB_OUTPUT
        elif [ -f rust-toolchain.toml ]; then
          # Extract channel securely, handling optional indentation, quotes, and trailing comments
          # using standard regex character classes for portability (BSD sed compat)
          VERSION=$(grep -E '^[[:space:]]*channel[[:space:]]*=' rust-toolchain.toml || true | sed -E 's/^[[:space:]]*channel[[:space:]]*=[[:space:]]*["'\'']?([^"'\'']+)["'\'']?([[:space:]]*#.*)?$/\1/')
          if [ -z "$VERSION" ]; then
             echo "Error: Could not extract channel from rust-toolchain.toml" >&2
             exit 1
          fi
          echo "toolchain=$VERSION" >> $GITHUB_OUTPUT
        else
          echo "Error: rust-version input is empty and rust-toolchain.toml not found." >&2
          exit 1
        fi

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
      with:
        toolchain: ${{ steps.version.outputs.toolchain }}
        components: ${{ inputs.components }}

    - name: Cache Cargo dependencies
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.2.2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
