name: 'Setup Rust Environment'
description: 'Installs Rust toolchain and configures reusable local Cargo directories for self-hosted runners'
inputs:
  rust-version:
    description: 'Rust toolchain version'
    required: false
    default: '1.90.0'
  components:
    description: 'Rust toolchain components to install (comma-separated, e.g., rustfmt,clippy)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Configure local Rust directories
      shell: bash
      run: |
        set -euo pipefail
        : "${GITHUB_ENV:?GITHUB_ENV must be set}"
        : "${GITHUB_PATH:?GITHUB_PATH must be set}"

        CACHE_ROOT="${RUNNER_TOOL_CACHE:-$HOME/.cache}/jlo-rust"
        REPO_SCOPE="${GITHUB_REPOSITORY:-local-repo}"
        REPO_SCOPE="${REPO_SCOPE//\//__}"

        RUSTUP_HOME_DIR="${CACHE_ROOT}/rustup"
        CARGO_HOME_DIR="${CACHE_ROOT}/cargo"
        CARGO_TARGET_DIR_VALUE="${CACHE_ROOT}/target/${REPO_SCOPE}"

        mkdir -p "${RUSTUP_HOME_DIR}" "${CARGO_HOME_DIR}" "${CARGO_TARGET_DIR_VALUE}"

        {
          echo "RUSTUP_HOME=${RUSTUP_HOME_DIR}"
          echo "CARGO_HOME=${CARGO_HOME_DIR}"
          echo "CARGO_TARGET_DIR=${CARGO_TARGET_DIR_VALUE}"
        } >> "${GITHUB_ENV}"
        echo "${CARGO_HOME_DIR}/bin" >> "${GITHUB_PATH}"

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
      with:
        toolchain: ${{ inputs.rust-version }}
        components: ${{ inputs.components }}
