name: 'Setup Rust Environment'
description: 'Checks out code, installs Rust, and caches Cargo dependencies'
inputs:
  rust-version:
    description: 'Rust toolchain version'
    required: false
    default: ''
  components:
    description: 'Rust toolchain components to install (comma-separated, e.g., rustfmt,clippy)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain (explicit version)
      if: inputs.rust-version != ''
      uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
      with:
        toolchain: ${{ inputs.rust-version }}
        components: ${{ inputs.components }}

    - name: Install Rust toolchain (from file)
      if: inputs.rust-version == ''
      uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
      with:
        components: ${{ inputs.components }}

    - name: Cache Cargo dependencies
      uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
