name: 'Install jlo'
description: 'Installs the jlo CLI binary pinned to .jlo/.jlo-version on the control branch with bounded local cache'

runs:
  using: 'composite'
  steps:
    - name: Install jlo
      shell: bash
      run: |
        set -euo pipefail
        : "${GITHUB_PATH:?GITHUB_PATH must be set}"

        if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
          echo "::error::install-jlo must run inside a git repository."
          exit 1
        fi

        if [ -z "${JLO_TARGET_BRANCH:-}" ]; then
          echo "::error::JLO_TARGET_BRANCH is required to install jlo."
          exit 1
        fi

        if ! git remote get-url origin >/dev/null 2>&1; then
          echo "::error::origin remote not found; cannot fetch ${JLO_TARGET_BRANCH}."
          exit 1
        fi

        echo "Fetching origin/${JLO_TARGET_BRANCH} for version pin..."
        if ! git fetch --quiet --depth=1 origin "${JLO_TARGET_BRANCH}"; then
          echo "::error::Failed to fetch ${JLO_TARGET_BRANCH} branch from origin."
          exit 1
        fi

        CONTROL_REF="origin/${JLO_TARGET_BRANCH}"
        VERSION_RAW="$(git show "${CONTROL_REF}:.jlo/.jlo-version" 2>/dev/null | tr -d '\r' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
        if [ -z "$VERSION_RAW" ]; then
          echo "::error::.jlo/.jlo-version is missing or empty on '${CONTROL_REF}'."
          exit 1
        fi

        VERSION="${VERSION_RAW#v}"
        TAG_VERSION="v${VERSION}"

        OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
        ARCH="$(uname -m)"

        case "$OS" in
          linux) OS="linux" ;;
          darwin) OS="darwin" ;;
          *)
            echo "::error::Unsupported OS for jlo install: $OS"
            exit 1
            ;;
        esac

        case "$ARCH" in
          x86_64|amd64) ARCH="x86_64" ;;
          arm64|aarch64) ARCH="aarch64" ;;
          *)
            echo "::error::Unsupported architecture for jlo install: $ARCH"
            exit 1
            ;;
        esac

        DEFAULT_CACHE_ROOT="${RUNNER_TOOL_CACHE:-$HOME/.cache}/jlo-bin-cache"
        if [ "${RUNNER_ENVIRONMENT:-}" = "github-hosted" ]; then
          DEFAULT_CACHE_ROOT="${RUNNER_TEMP:-/tmp}/jlo-bin-cache"
        fi

        CACHE_ROOT="${JLO_CACHE_ROOT:-${DEFAULT_CACHE_ROOT}}"
        if ! mkdir -p "${CACHE_ROOT}" >/dev/null 2>&1; then
          CACHE_ROOT="${RUNNER_TEMP:-/tmp}/jlo-bin-cache"
          mkdir -p "${CACHE_ROOT}"
        fi

        PLATFORM_DIR="${CACHE_ROOT}/${OS}-${ARCH}"
        INSTALL_DIR="${PLATFORM_DIR}/${TAG_VERSION}"
        BIN_PATH="${INSTALL_DIR}/jlo"

        mkdir -p "${INSTALL_DIR}"

        if [ -x "${BIN_PATH}" ]; then
          CACHED_VERSION="$("${BIN_PATH}" --version 2>/dev/null | tr -d '\r' | grep -o -E '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1 || true)"
          if [ -n "${CACHED_VERSION}" ] && [ "${CACHED_VERSION}" = "${VERSION}" ]; then
            echo "✅ jlo ${VERSION} already cached; skipping download."
          else
            rm -f "${BIN_PATH}"
          fi
        fi

        if [ ! -x "${BIN_PATH}" ]; then
          ASSET="jlo-${OS}-${ARCH}"
          URL="https://github.com/akitorahayashi/jlo/releases/download/${TAG_VERSION}/${ASSET}"

          echo "Installing jlo ${VERSION} from: ${URL}"
          TMP_BIN="$(mktemp "${RUNNER_TEMP:-/tmp}/jlo-download.XXXXXX")"
          trap 'rm -f "${TMP_BIN}"' EXIT

          curl --fail --silent --show-error --location \
            --connect-timeout 10 \
            --max-time 60 \
            --retry 3 \
            --retry-delay 2 \
            --retry-all-errors \
            "${URL}" -o "${TMP_BIN}"
          chmod +x "${TMP_BIN}"
          mv "${TMP_BIN}" "${BIN_PATH}"
          trap - EXIT
        fi

        # Keep only the pinned version for this OS/arch to prevent accumulation.
        if [ -d "${PLATFORM_DIR}"; then
          find "${PLATFORM_DIR}" -mindepth 1 -maxdepth 1 -type d ! -name "${TAG_VERSION}" -exec rm -rf {} +
        fi

        echo "${INSTALL_DIR}" >> "${GITHUB_PATH}"
        echo "✅ jlo installed: $("${BIN_PATH}" --version 2>/dev/null || echo 'version unknown')"
