# Jules Agent Execution
#
# Workflow template for repositories using jlo.
# Copy to .github/workflows/jules.yml in target repository.
#
# Prerequisites:
# 1. Run `jlo init` to create .jules/ structure
# 2. Set JULES_API_KEY secret in repository settings
# 3. Install jlo release binary (automatic via workflow)

name: Jules Agents

on:
  schedule:
    # Daily at 19:00 UTC - adjust as needed
    - cron: '0 19 * * *'
  workflow_dispatch:
    inputs:
      layer:
        description: 'Agent layer to run'
        required: true
        type: choice
        options:
          - observers
          - deciders
          - planners
          - implementers
      role:
        description: 'Specific role (optional, comma-separated)'
        required: false
        type: string
      dry_run:
        description: 'Show prompts without executing'
        required: false
        type: boolean
        default: false
      jlo_version:
        description: 'jlo release tag (e.g. v2.0.0) or "latest"'
        required: false
        type: string
        default: 'latest'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  scheduled:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    env:
      JLO_VERSION: ${{ vars.JLO_VERSION || 'latest' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: jules

      - name: Install jlo
        run: |
          VERSION="${JLO_VERSION}"
          if [ -z "$VERSION" ]; then
            VERSION="latest"
          fi
          if [ "$VERSION" != "latest" ] && [ "${VERSION#v}" = "$VERSION" ]; then
            VERSION="v${VERSION}"
          fi
          if [ "$VERSION" = "latest" ]; then
            URL="https://github.com/akitorahayashi/jlo/releases/latest/download/jlo-linux-x86_64"
          else
            URL="https://github.com/akitorahayashi/jlo/releases/download/${VERSION}/jlo-linux-x86_64"
          fi
          curl -sSL "$URL" -o jlo
          chmod +x jlo && sudo mv jlo /usr/local/bin/

      - name: Run observers
        env:
          JULES_API_KEY: ${{ secrets.JULES_API_KEY }}
        run: jlo run observers

  manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      JLO_VERSION: ${{ inputs.jlo_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.layer == 'implementers' && 'main' || 'jules' }}

      - name: Install jlo
        run: |
          VERSION="${JLO_VERSION}"
          if [ -z "$VERSION" ]; then
            VERSION="latest"
          fi
          if [ "$VERSION" != "latest" ] && [ "${VERSION#v}" = "$VERSION" ]; then
            VERSION="v${VERSION}"
          fi
          if [ "$VERSION" = "latest" ]; then
            URL="https://github.com/akitorahayashi/jlo/releases/latest/download/jlo-linux-x86_64"
          else
            URL="https://github.com/akitorahayashi/jlo/releases/download/${VERSION}/jlo-linux-x86_64"
          fi
          curl -sSL "$URL" -o jlo
          chmod +x jlo && sudo mv jlo /usr/local/bin/

      - name: Parse role input
        id: parse
        run: |
          if [ -n "${{ inputs.role }}" ]; then
            roles=$(echo "${{ inputs.role }}" | tr ',' '\n' | sed 's/^/--role /' | tr '\n' ' ')
            echo "role_args=$roles" >> "$GITHUB_OUTPUT"
          else
            echo "role_args=" >> "$GITHUB_OUTPUT"
          fi

      - name: Run agents
        env:
          JULES_API_KEY: ${{ secrets.JULES_API_KEY }}
        run: |
          ARGS=""
          if [ "${{ inputs.dry_run }}" = "true" ]; then
            ARGS="$ARGS --dry-run"
          fi
          jlo run ${{ inputs.layer }} ${{ steps.parse.outputs.role_args }}$ARGS
