name: Jules Invoke
description: 'Invoke Jules, an AI-powered coding agent, to perform tasks on your codebase.'

branding:
  icon: 'code'
  color: 'purple'

inputs:
  prompt:
    description: 'The prompt to pass to Jules'
    required: true
    type: string
  include_last_commit:
    description: 'Whether to pass content of the last commit'
    type: boolean
    default: false
  include_commit_log:
    description: 'Whether to pass commit history'
    type: boolean
    default: false
  starting_branch:
    description: 'The branch for Jules to start from'
    required: false
    type: string
    default: 'main'
  jules_api_key:
    description: 'The Jules API key to use for authentication'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 30

    - name: Create initial prompt
      env:
        USER_PROMPT: ${{ inputs.prompt }}
      shell: bash
      run: |
        echo "$USER_PROMPT" > prompt.txt

    - name: Save last commit content
      if: ${{ inputs.include_last_commit }}
      shell: bash
      run: |
        echo -e '\n\nContent of the latest commit (in the format of `git show`):' >> prompt.txt
        echo '```' >> prompt.txt
        git show   >> prompt.txt
        echo '```' >> prompt.txt

    - name: Save git log
      if: ${{ inputs.include_commit_log }}
      shell: bash
      run: |
        echo -e '\n\nLog of the last 20 commits (in the format of `git log --stat`):' >> prompt.txt
        echo '```'         >> prompt.txt
        git log -20 --stat >> prompt.txt
        echo '```'         >> prompt.txt

    - name: Assemble Jules payload
      shell: bash
      run: |
        jq -n --arg jules_prompt "$(cat prompt.txt)" --arg starting_branch "${{ inputs.starting_branch }}" --arg repo_full_name "${{ github.repository }}" '{
            "prompt": $jules_prompt,
            "sourceContext": {
              "source": "sources/github/\($repo_full_name)",
              "githubRepoContext": {
                "startingBranch": $starting_branch
              }
            },
            "requirePlanApproval": false,
            "automationMode": "AUTO_CREATE_PR"
          }' > jules_payload.json

    - name: Invoke Jules
      shell: bash
      run: |
        curl 'https://jules.googleapis.com/v1alpha/sessions' \
          -X POST \
          -H "Content-Type: application/json" \
          -H "X-Goog-Api-Key: ${{ inputs.jules_api_key }}" \
          -d @jules_payload.json
