name: 'Read Role Prompt'
description: 'Read prompt.yml from a Jules role directory'
inputs:
  layer:
    description: 'Layer name (observers, deciders, planners)'
    required: true
  role:
    description: 'Role name within the layer'
    required: true
outputs:
  prompt:
    description: 'The prompt content'
    value: ${{ steps.read.outputs.content }}

runs:
  using: 'composite'
  steps:
    - name: Read prompt.yml
      id: read
      shell: bash
      run: |
        prompt_path=".jules/roles/${{ inputs.layer }}/${{ inputs.role }}/prompt.yml"
        if [ ! -f "$prompt_path" ]; then
          echo "Error: prompt.yml not found at $prompt_path"
          exit 1
        fi
        content=$(cat "$prompt_path")
        echo "content<<EOF" >> "$GITHUB_OUTPUT"
        echo "$content" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"
