name: 'Install jlo'
description: 'Downloads and installs the jlo CLI binary (self-hosted friendly)'
inputs:
  version:
    description: 'jlo version to install (e.g., "v5.0.0", "5.0.0", or "latest")'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Install jlo
      shell: bash
      run: |
        set -euo pipefail
        VERSION="${{ inputs.version }}"

        : "${GITHUB_PATH:?GITHUB_PATH must be set}"

        # Normalize version format
        if [ "$VERSION" != "latest" ] && [ "${VERSION#v}" = "$VERSION" ]; then
          VERSION="v${VERSION}"
        fi

        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)

        case "$OS" in
          linux) OS="linux" ;;
          darwin) OS="darwin" ;;
          *)
            echo "::error::Unsupported OS for jlo install: $OS"
            exit 1
            ;;
        esac

        case "$ARCH" in
          x86_64|amd64) ARCH="x86_64" ;;
          arm64|aarch64) ARCH="aarch64" ;;
          *)
            echo "::error::Unsupported architecture for jlo install: $ARCH"
            exit 1
            ;;
        esac

        ASSET="jlo-${OS}-${ARCH}"

        # Construct download URL
        if [ "$VERSION" = "latest" ]; then
          URL="https://github.com/akitorahayashi/jlo/releases/latest/download/${ASSET}"
        else
          URL="https://github.com/akitorahayashi/jlo/releases/download/${VERSION}/${ASSET}"
        fi

        echo "Installing jlo from: $URL"
        curl --fail --silent --show-error --location \
          --connect-timeout 10 \
          --max-time 60 \
          --retry 3 \
          --retry-delay 2 \
          --retry-all-errors \
          "$URL" -o jlo
        chmod +x jlo

        INSTALL_DIR="${RUNNER_TEMP:-/tmp}/jlo-bin"
        mkdir -p "$INSTALL_DIR"
        mv jlo "$INSTALL_DIR/jlo"

        echo "$INSTALL_DIR" >> "$GITHUB_PATH"
        echo "✅ jlo installed: $($INSTALL_DIR/jlo --version 2>/dev/null || echo 'version unknown')"
