schema_version: 1

# Metadata
id: "__EVENT_ID__"
created_at: "__EVENT_DATE__"
author_role: "__ROLE__"
category: "__CATEGORY__"
confidence: "medium"

# Content
title: "__EVENT_TITLE__"
statement: |
  __EVENT_STATEMENT__

evidence:
  - path: "__EVIDENCE_PATH__"
    loc: "__EVIDENCE_LOC__"
    note: "__EVIDENCE_NOTE__"

tags:
  - "__EVENT_TAG__"
