name: 'Wait for Jules Processing'
description: 'Waits for Jules async processing with progress updates'
inputs:
  wait_minutes:
    description: 'Minutes to wait'
    required: true
  mock_mode:
    description: 'Mock mode flag'
    required: false
    default: 'false'
  process_name:
    description: 'Name of the process being waited for'
    required: false
    default: ''
outputs:
  json:
    description: 'JSON output'
    value: '{}'
runs:
  using: 'composite'
  steps:
    - name: Wait for Jules async processing
      shell: bash
      run: |
        set -euo pipefail
        trap 'echo "Cancellation detected. Exiting wait early."; exit 130' INT TERM

        if [ "${{ inputs.mock_mode }}" = "true" ]; then
          TOTAL_SECONDS=30
          echo "Mock mode enabled: overriding wait to 30 seconds."
        else
          TOTAL_SECONDS=$((${{ inputs.wait_minutes }} * 60))
        fi

        if [ "$TOTAL_SECONDS" -le 0 ]; then
          echo "Wait skipped (TOTAL_SECONDS=$TOTAL_SECONDS)."
          exit 0
        fi

        if [ -n "${{ inputs.process_name }}" ]; then
          echo "Waiting ${TOTAL_SECONDS} seconds for Jules to process ${{ inputs.process_name }}..."
        else
          echo "Waiting ${TOTAL_SECONDS} seconds for Jules to process..."
        fi
        ELAPSED=0
        INTERVAL=5
        while [ $ELAPSED -lt $TOTAL_SECONDS ]; do
          STEP=$INTERVAL
          REMAINING=$((TOTAL_SECONDS - ELAPSED))
          if [ "$REMAINING" -lt "$STEP" ]; then
            STEP=$REMAINING
          fi
          sleep "$STEP" &
          wait $!
          ELAPSED=$((ELAPSED + STEP))
          echo "[$ELAPSED/$TOTAL_SECONDS seconds]"
        done
        echo "Wait complete."
